id = "php-snippets"
name = "PHP Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Tejas Shinde"]
description = "A collection of PHP snippets for Zed IDE."
repository = ""
snippets = ["./snippets/php.json"]
